// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDwcJ87hlRgRwxj1EvMmHWU7rANhKhQHM',
    appId: '1:1055160119566:web:7a2dcf6953c1561329275f',
    messagingSenderId: '1055160119566',
    projectId: 'gridwise-5392a',
    authDomain: 'gridwise-5392a.firebaseapp.com',
    storageBucket: 'gridwise-5392a.firebasestorage.app',
    measurementId: 'G-VFR28V04SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QtrdlTGOXyLDQw_kmI6iIlbaaqxCx_U',
    appId: '1:1055160119566:android:09f18af76025468c29275f',
    messagingSenderId: '1055160119566',
    projectId: 'gridwise-5392a',
    storageBucket: 'gridwise-5392a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsA7K4ALQ7DxVioZVlwzWteDGJSE-8NM',
    appId: '1:1055160119566:ios:9770b21199c68c8e29275f',
    messagingSenderId: '1055160119566',
    projectId: 'gridwise-5392a',
    storageBucket: 'gridwise-5392a.firebasestorage.app',
    iosClientId: '1055160119566-b6p4rgedf4jllgqo44ch38vnff82qcf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gridwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsA7K4ALQ7DxVioZVlwzWteDGJSE-8NM',
    appId: '1:1055160119566:ios:9770b21199c68c8e29275f',
    messagingSenderId: '1055160119566',
    projectId: 'gridwise-5392a',
    storageBucket: 'gridwise-5392a.firebasestorage.app',
    iosClientId: '1055160119566-b6p4rgedf4jllgqo44ch38vnff82qcf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gridwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDwcJ87hlRgRwxj1EvMmHWU7rANhKhQHM',
    appId: '1:1055160119566:web:fc88ae99d82dae8629275f',
    messagingSenderId: '1055160119566',
    projectId: 'gridwise-5392a',
    authDomain: 'gridwise-5392a.firebaseapp.com',
    storageBucket: 'gridwise-5392a.firebasestorage.app',
    measurementId: 'G-TKGXJVGWFZ',
  );

}